// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vutwszfntzxnnycdfuum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1dHdzemZudHp4bm55Y2RmdXVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NzY5MTEsImV4cCI6MjA2MjQ1MjkxMX0.LR99u9KmamggEQora4mI_Qh4w7MG8HreSD-4spMQZP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);